### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by asklar** [hughbe/OutlookRulesReader#6]
Hi @hughbe, which license is this distributed under?

**Comment by asklar** [comment]
thanks!

**Comment by hughbe** [comment]
If this is too restrictive for your purposes let me know - I am flexible :)

**Comment by asklar** [comment]
I've adapted the code / specs to typescript. My goal is to output the rules as json: https://github.com/asklar/rwzreader
I did find some issues with the original code/spec... in retrospect I should have taken notes but I forgot, sorry about that :( 
IIRC there is additional padding needed between rules (but not for the last rule) which wasn't called out in the spec. I'm sure I've probably introduced a bug or three in my impl (I don't have to care about older than 2019 so this simplifies things a bit), but this is a good starting point :)

**Comment by hughbe** [comment]
Could I ask about your use case? Would be interested in finding out!
